app_state:
  cache_enabled: false
  notification_enabled: true
  workspace: DEV
llm:
  model: gpt-4o-mini
  provider: OpenAI
  default_provider: "Ollama (Local)" 
  default_model: "mistral:latest"
  timeout:
    connect: 10  # Connection timeout in seconds
    read: 300    # Read timeout in seconds
logging:
  level: INFO
  max_log_entries: 1000
tools:
  everything:
    cli_path: C:\Program Files\Everything\es.exe
    gui_path: C:\Program Files\Everything\Everything.exe
ui:
  theme: default
