app_state:
  cache_enabled: false
  notification_enabled: true
  role: Self
  workspace: PERSONAL
llm:
  default_model: mistral:latest
  default_provider: Ollama (Local)
  model: gpt-4o-mini
  provider: OpenAI
  timeout:
    connect: 10
    read: 300
logging:
  level: INFO
  max_log_entries: 1000
tools:
  everything:
    cli_path: C:\Program Files\Everything\es.exe
    gui_path: C:\Program Files\Everything\Everything.exe
ui:
  theme: default

# RAG Configuration
rag:
  enabled: true
  agents:
    - chat  # Liste des agents qui utilisent RAG
  vector_db:
    path: "data/vector_db"  # Chemin unique pour la base ChromaDB
  config:
    max_results: 3
    min_similarity: 0.7
    importance_filter: "High"
