app_state:
  cache_enabled: false
  notification_enabled: true
  role: Self
  workspace: PERSONAL
llm:
  default_model: mistral:latest
  default_provider: Ollama (Local)
  model: gpt-4o-mini
  provider: OpenAI
  timeout:
    connect: 10
    read: 300
logging:
  level: INFO
  max_log_entries: 1000
tools:
  everything:
    cli_path: C:\Program Files\Everything\es.exe
    gui_path: C:\Program Files\Everything\Everything.exe
ui:
  theme: default
