# Application Configuration
app:
  name: JarvisOne
  version: 0.1.0

# UI Configuration
ui:
  theme: light
  layout: wide
  sidebar_width: 300

# Logging Configuration
logging:
  level: DEBUG
  format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"

# LLM Configuration
llm:
  provider: OpenAI
  model: gpt-4o-mini
  max_tokens: 2000
  temperature: 0.7

# Tool Configuration
tools:
  everything:
    cli_path: "C:\\Program Files\\Everything\\es.exe"
    gui_path: "C:\\Program Files\\Everything\\Everything.exe"

# Vector DB Configuration
vector_db:
  collection_prefix: workspace_
  collection_settings:
    chunk_overlap: 200
    chunk_size: 1000
    distance_metric: cosine
    embedding_function: sentence-transformers/all-MiniLM-L6-v2
  monitoring:
    log_queries: true
    metrics_enabled: true
    performance_threshold_ms: 1000
  path: data/vector_db

# RAG Configuration
rag:
  agents:
    - chat_agent
  config:
    importance_filter: High
    max_results: 3
    max_tokens: 4000
    min_similarity: 0.7
  document_processing:
    max_file_size_mb: 10
    supported_extensions:
      - .txt
      - .pdf
      - .docx
      - .xlsx
      - .pptx
      - .epub
      - .md
      - .json
  enabled: true

# Data Directory
data_dir: data

# App State
app_state:
  cache_enabled: false
  notification_enabled: true
  role: Coach
  workspace: COACHING
